add plugin support
samvera-labs/clover-iiif pull request #183
Opened 2024-03-13 21:08 UTC by wykhuh

@adamjarling @mathewjordan These are changes I made Clover in order to support plugins. The two parts that I changed for the annotation plugin was to give the plugin access to the Image Viewer Controls and Information Panel.

2024-04-19 21:16 UTC, wykhuh commented
@adamjarling @mathewjordan I updated plugins to Clover 2.7.5.

2024-05-22 13:53 UTC, mathewjordan reviewed
🥇 Overall, this looks pretty good to me. I'll chat through it with @adamjarling now that I grok it well enough. If there are changes, I think they will be pretty minimal and mostly organizational.

2024-05-22 15:33 UTC, adamjarling commented on src/types/plugins.ts
> +}
Maybe `extend` PluginInformationPanel?

```ts
export interface PluginInformationPanel extends Plugin {
  annotations?: Annotation[];
}
```

2024-05-22 15:41 UTC, adamjarling commented on src/index.tsx
> +  type PluginInformationPanel,
I also wonder if there's cleaner way to handle these exports, or group or title them to clarify their context to future consumers of the package?

2024-05-22 16:50 UTC, wykhuh commented
> @wykhuh @mathewjordan Should we add some documentation?

I was going to add documentation after y'all looked the PR. I wanted us to figure out the api for plugins before writing the documentations.

Another thing to think about: will Clover website have a page that lists the custom displays and plugins that are available for Clover?

2024-05-22 17:29 UTC, wykhuh commented
@mathewjordan @adamjarling You two have edit access to my forked repo, so feel free to make edits and commits to this branch.

2024-05-23 16:37 UTC, mathewjordan requested changes
A few notes:

- Add plugins docs in Viewer
- Consolidate helpers under one export 

```
  'helpers': {
    lib: {
      name: "CloverIIIFHelpers",
      entry: "./src/lib/index.ts", // pile them through here
      fileName: "index",
    },
  }
```

- Rename `imageViewer.menu` to `imageViewer.controls`
- If you'd like, add a Plugins page under Composing in the documentation nav
- Adam's note about extending types where possible

2024-05-23 16:37 UTC, mathewjordan commented on src/context/viewer-context.tsx
> +    menu?: {
```suggestion
    controls?: {
```

2024-05-23 16:37 UTC, mathewjordan commented on src/types/plugins.ts
> +}
Agree here.

2024-05-24 15:49 UTC, wykhuh commented on build/build.mjs
> +      fileName: "index",
I consolidated the helpers in a single export

2024-05-24 15:50 UTC, wykhuh commented on src/context/viewer-context.tsx
> +    menu?: {
I changed it to imageViewer.controls

2024-05-24 16:08 UTC, wykhuh commented
@mathewjordan @adamjarling I mage the suggested changes. I also add plugin docs to the viewer page. Could you review the docs to see if it makes sense?

2024-05-24 16:20 UTC, mathewjordan commented
> @mathewjordan @adamjarling I mage the suggested changes. I also add plugin docs to the viewer page. Could you review the docs to see if it makes sense?

Sure thing.

2024-05-24 21:59 UTC, wykhuh commented on src/index.tsx
> +  type PluginInformationPanel,
@mathewjordan I exported a consolidated helpers.

2024-05-28 21:14 UTC, mathewjordan approved these changes

2024-05-28 21:14 UTC, merged