Fix blank page aside rendering bug on initial load
samvera-labs/clover-iiif pull request #187
Opened 2024-03-14 14:13 UTC by adamjarling

## What does this do?
Quick patch to account for a state where:
- `InformationPanel` should not be open by default
- "About" in `InformationPanel` configured to be `true`
- No annotation resources exist

It results in the Viewer initially rendering like this.  Note the space where the `InformationPanel` displays (not good)

![image](https://github.com/samvera-labs/clover-iiif/assets/3020266/0651ea08-5b49-413c-b388-90b70ee020d6)

## How to test
With default configuration, run in your dev environment and the initial render should not display empty space to the right of the Viewer Content:

![image](https://github.com/samvera-labs/clover-iiif/assets/3020266/357d3bda-5a4c-49a9-a940-fb414009c1f1)

2024-03-14 14:33 UTC, tpendragon commented
Oh I think I fixed this in https://github.com/samvera-labs/clover-iiif/pull/185 by removing the <Aside> container, which could enable some CSS transitions, but whatever y'all think is best.

2024-03-14 19:16 UTC, mathewjordan requested changes
@adamjarling This is close but it's not quite correct with Manifests that have annotations (VTT or otherwise). It does behave as expected where it renders the aside, however if the aside is toggled off, the canvas does not grow to take the removed space.

See with:

- VTT: https://digital.lib.utk.edu/assemble/manifest/rfta/118
- Simple Tagging Annotation - https://iiif.io/api/cookbook/recipe/0021-tagging/manifest.json

2024-03-14 21:04 UTC, adamjarling commented
> @adamjarling This is close but it's not quite correct with Manifests that have annotations (VTT or otherwise). It does behave as expected where it renders the aside, however if the aside is toggled off, the canvas does not grow to take the removed space.
> 
> See with:
> 
> * VTT: https://digital.lib.utk.edu/assemble/manifest/rfta/118
> * Simple Tagging Annotation - https://iiif.io/api/cookbook/recipe/0021-tagging/manifest.json

@mathewjordan Ok, just pushed up what should be a fix.  Trying to capture this with tests, feels a little brittle.  [Playwright](https://playwright.dev/)/Cypress to the rescue might save some time here in the future.

2024-03-15 15:55 UTC, mathewjordan approved these changes

2024-03-15 18:14 UTC, merged